### ISSUE TITLE
Is this repository still being maintained?

### ISSUE THREAD

**Issue by talex5** [capnproto/capnp-ocaml#12]
If not, I can set up a new project (maybe under https://github.com/mirage) for people to continue working on it.

**Comment by pelzlpj** [comment]
On Wed, May 3, 2017 at 7:57 AM Thomas Leonard <notifications@github.com>
wrote:

> If not, I can set up a new project (maybe under https://github.com/mirage)
> for people to continue working on it.
>

I'm still here, but your PRs dropped right in the middle of crunch time at
work. :-)

I should have some time to catch up next week. Please ping me if I don't
follow through.

Paul


>

**Comment by talex5** [comment]
Ah, great. I'll continue submitting things here then. Apart from general cleanups, I want to have support for RPC. I now have a basic level 0 service working, using the code in my `interfaces` branch, but it needs cleaning up. Did you have any particular plans in this direction?

**Comment by pelzlpj** [comment]
On Thu, May 4, 2017 at 4:10 AM Thomas Leonard <notifications@github.com>
wrote:

> Ah, great. I'll continue submitting things here then. Apart from general
> cleanups, I want to have support for RPC. I now have a basic level 0
> service working, using the code in my interfaces branch, but it needs
> cleaning up. Did you have any particular plans in this direction?
>

That would be awesome. I have no near-term plans to look at RPC, and would
be pleased to pull in your work.

My own priority was to look into supporting generics... but my time has
been pretty limited.

Paul

**Comment by pelzlpj** [comment]
All caught up!

**Comment by talex5** [comment]
@avsm has pointed out that I was a bit unclear here: if we moved this repository under `mirage`, you would still have commit access. However, it would allow other people to merge PRs and make releases too, avoiding the risk of one person becoming a bottleneck when they're busy with other projects.

If so, the likely direction would be to remove camlp4, remove any dependencies that prevent it from running as a unikernel, update the build system to jbuild, etc, which you might or might not be happy about...

**Comment by pelzlpj** [comment]
> If so, the likely direction would be to remove camlp4

Good, very much in favor.

> remove any dependencies that prevent it from running as a unikernel, 

Good, unikernels are awesome.

> update the build system to jbuild, etc, which you might or might not be happy about...

Good, I'm not really sold on OMake.

Between these sensible next steps and and my continuing limited time, I'm convinced. Do you need me to do anything to make this happen?

**Comment by avsm** [comment]
Hi @pelzlpj, thanks for this! If you give me admin rights to this repository, I can execute the repo transfer, and add you to the mirage org so that you continue to have push rights to the repo over there, along with @talex5.

**Comment by talex5** [comment]
Note: I think you (@pelzlpj) will need to transfer the repository first to @avsm, since you might not be able to give someone else admin rights on a personal repository:

1. Go to Settings -> Options -> Danger Zone -> Transfer ownership
2. Transfer it to "avsm" (I think this is better than using my account, as I already have a fork of it and that might confuse things).
3. Anil can then transfer it to mirage and fix up the permissions.

Then the mirage copy becomes the official one, and we'll get to keep all the issues and PRs.

**Comment by avsm** [comment]
Sure, that works for me too.

**Comment by talex5** [comment]
@pelzlpj - are you OK to do the transfer now?

**Comment by kentonv** [comment]
Hey guys,

I'm currently thinking it would be nice to move all the Cap'n Proto repositories under a single Cap'n Proto organization. I think it would be easier for people to understand and would make maintainership transfers easier in the future as well (since URLs wouldn't change, etc.).

But if you were excited about having this under your org, I don't want to steal that from you.

What do you think?

**Comment by kentonv** [comment]
More info: https://groups.google.com/d/msg/capnproto/8WxFB0Dij_c/J48Wbcg4AQAJ

FWIW I'd like to set this up probably tomorrow-ish.

**Comment by pelzlpj** [comment]
I'm going to move forward with transferring ownership to @avsm because I have pretty good confidence that the Mirage folks will exercise good judgment moving forward. If they want to get this under the capnproto organizational umbrella, that's fine too... but my biggest concern right now is preventing myself from being a bottleneck.

**Comment by talex5** [comment]
Moving it under either capnproto or mirage is fine with me.

**Comment by avsm** [comment]
Many thanks for this @pelzlpj.

@kentonv, we'd be happy to have all the Cap'n Proto libraries in one place, so your organisation makes a lot of sense and is more discoverable for the wider community.  If you give @talex5 @pelzlpj and me access to the repo in there, that should be fine to start with.  I can also post on <https://discuss.ocaml.org> once it has been transferred, to let the OCaml community know.

**Comment by avsm** [comment]
@kentonv I temporarily need access to create repositories on the `capnproto` org in order to initiate the repo transfer.

**Comment by kentonv** [comment]
@avsm invite sent

**Comment by avsm** [comment]
And transfer complete!  Now that we've found ourselves a new home, I will close this issue after the RPC library also finds a new home and we sent the announcement on https://discuss.ocaml.org

**Comment by kentonv** [comment]
@avsm Great! I've now converted you to "outside collaborator" on the organization, with write access to this repo. Let me know if that causes any problems in which case I can put you back in the org, but I like to use good security hygiene where possible. :)

**Comment by avsm** [comment]
@talex5 our convention is to have the libraries named `ocaml-*`, and I notice the node library here is also `node-capnp`. Mind if I rename this repository to `ocaml-capnp`?

**Comment by avsm** [comment]
@kentonv absolutely -- minimising privileges is also preferred on our side to minimise our cognitive stress with too many github orgs/responsibilities :-) thanks!

**Comment by talex5** [comment]
@avsm: I don't mind either way, but @kentonv should decide the naming scheme for the organisation. I suspect the name comes from the name of the compiler plugin it builds (which puts the capnp first).

BTW, could someone give me write access to the new repo?

**Comment by avsm** [comment]
That makes sense; I'll leave it the way it is now. I don't have admin rights to this any more, so @kentonv will have to add @talex5 and @pelzlpj to merge.

**Comment by avsm** [comment]
@kentonv would it be possible for some of us to get admin rights to this particular repo so we can add more users than just me? I would also like to setup Travis CI testing, which needs admin.

**Comment by kentonv** [comment]
@avsm Oops, sorry, I'd assumed you already were admin since you created the repo. I've now made you and Paul admin, and also added @talex5 with write access, though feel free to make him admin too -- this is your repo so do as you see fit.

**Comment by talex5** [comment]
Thanks @kentonv - I have write access now!

**Comment by avsm** [comment]
thanks @kentonv!
