### ISSUE TITLE
rename to ocaml-capnp

### ISSUE THREAD

**Issue by samoht** [capnproto/capnp-ocaml#27]
Other projects are called `foo-capnp` (where `foo` is `node` or `py`(thon)) and this is more consistent with the OCaml conventions as well.

**Comment by talex5** [comment]
See: https://github.com/capnproto/capnp-ocaml/issues/12#issuecomment-306246779

**Comment by talex5** [comment]
There's a mix - we also have `capnproto-rust` and `capnproto-java`. Closing this, as I don't think we're going to change it.
