### ISSUE TITLE
reevaluate benefits of defunctorization with OCaml >= 4.03

### ISSUE THREAD

**Issue by pelzlpj** [capnproto/capnp-ocaml#7]
OCaml 4.03 features the new 'flambda' optimization framework, which promises to improve inlining in many contexts. It's possible that this optimization eliminates the benefit of defunctorization, in which case capnp-ocaml could switch over to a cleaner functor-only model.

**Comment by talex5** [comment]
#23 switched to using flambda inlining, which seems to be even faster than defunctorization (without flambda).
