### ISSUE TITLE
LICENSE for capnp-ocaml

### ISSUE THREAD

**Issue by tmcgilchrist** [capnproto/capnp-ocaml#78]
What license is this repository under?

The new [ocaml](https://v3.ocaml.org/p/capnp/3.4.0) documentation site says `No License` because the opam file doesn't mention anything.

Could I suggest moving the license text into a LICENSE file and modifying the opam files to spell out which license? Happy to do the manual work to make that happen with opam.

**Comment by talex5** [comment]
Sounds good to me!

**Comment by tmcgilchrist** [comment]
Merged
