### ISSUE TITLE
Add Warning 55 inlining-impossible to suppression list

### ISSUE THREAD

**Issue by jonahbeckford** [capnproto/capnp-ocaml#86]
Versions:
* capnp-ocaml.3.5.0
* dune.3.6.2
* ocaml.4.14.0

On Windows MSVC (but I don't think it matters).

I get the following:

```
File "src/HelloWorld/schema.ml", line 93, characters 10-65:
93 |   include Capnp.Runtime.BuilderInc.Make[@inlined](MessageWrapper)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Warning 55 [inlining-impossible]: Cannot inline: Unknown function
File "src/HelloWorld/schema.ml", line 202, characters 36-72:
202 | module Make(M:Capnp.MessageSig.S) = MakeRPC[@inlined](Capnp.RPC.None(M)) [@@inline]
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Warning 55 [inlining-impossible]: Cannot inline: Function information unavailable
```

generated from the schema:

```
@0xed41535c2280ba70; # unique file ID, generated by `capnp id`

# This section is used by capnproto-java only
using Java = import "/capnp/java.capnp";
$Java.package("com.diskuv.examples.helloworldactor");
$Java.outerClassname("Schema");

struct Greet {
  whom @0 :Text;
  replyTo @1 :Data;
}

struct Greeted {
  whom @0 :Text;
  from @1 :Data;
}
```

The generated `schema.ml` starts with:

```
[@@@ocaml.warning "-27-32-37-60"]
```

Can we add `-55` to that suppression list?

**Comment by talex5** [comment]
Good idea! PRs welcome. You might need to use `-53` as well (I see some projects using that).

(the problem is that inlining attributes needed for flambda generate warnings without it)

**Comment by jonahbeckford** [comment]
Interesting. Apparently `-55` is [one of the undocumented attributes that can't be done with `ocaml.warning`](https://v2.ocaml.org/manual/attributes.html#ss:builtin-attributes). At least with OCaml 4.14.0 when I tested it.

Sigh. Okay. "Close as not planned" due to inability to control inside the generated code.
