### ISSUE TITLE
port from ocaml-uint to ocaml-stdint

### ISSUE THREAD

**Issue by pelzlpj** [capnproto/capnp-ocaml#9]
`uint` has apparently been superceded by `stdint`. We should target the latest and greatest.
https://github.com/andrenth/ocaml-stdint

**Comment by talex5** [comment]
It seems there may be some problems with stdint (e.g. https://github.com/inhabitedtype/angstrom/issues/33).

<https://github.com/ocamllabs/ocaml-integers> is another possibility, while we wait for <https://caml.inria.fr/mantis/view.php?id=7280>.

**Comment by liyishuai** [comment]
Should the README be updated as well?
https://github.com/capnproto/capnp-ocaml/blob/74633cf0e7e937de9a51a4ec73611fb32f7719ef/README.adoc?plain=1#L40-L41
